/**
 * Generates admin-ui/src/utils/processMetadataLabels.js from metadata/processes/*.json
 * Run from repo root: node scripts/generate_process_metadata_labels.js
 */
const fs = require('fs')
const path = require('path')

const root = path.join(__dirname, '..')
const dir = path.join(root, 'metadata', 'processes')
const STATE_LABELS_FA = {}
const PROCESS_LABELS_FA = {}
const STUDENT_TASK_LABELS_FA = {}
const OPERATOR_TASK_LABELS_FA = {}
const PROCESS_STATE_LABELS_FA = {}
const PROCESS_STUDENT_TASK_LABELS_FA = {}
const PROCESS_OPERATOR_TASK_LABELS_FA = {}

for (const f of fs.readdirSync(dir).filter((x) => x.endsWith('.json'))) {
  try {
    const j = JSON.parse(fs.readFileSync(path.join(dir, f), 'utf8'))
    const procCode = j.process?.code
    if (procCode && j.process?.name_fa) {
      PROCESS_LABELS_FA[procCode] = j.process.name_fa
    }
    if (procCode) {
      if (!PROCESS_STATE_LABELS_FA[procCode]) PROCESS_STATE_LABELS_FA[procCode] = {}
      if (!PROCESS_STUDENT_TASK_LABELS_FA[procCode]) PROCESS_STUDENT_TASK_LABELS_FA[procCode] = {}
      if (!PROCESS_OPERATOR_TASK_LABELS_FA[procCode]) PROCESS_OPERATOR_TASK_LABELS_FA[procCode] = {}
    }
    for (const s of j.states || []) {
      if (s.code && s.name_fa && !STATE_LABELS_FA[s.code]) {
        STATE_LABELS_FA[s.code] = s.name_fa
      }
      if (procCode && s.code && s.name_fa) {
        PROCESS_STATE_LABELS_FA[procCode][s.code] = s.name_fa
      }
      const taskFa = (s.metadata?.student_task_fa || '').trim()
      if (s.code && taskFa && !STUDENT_TASK_LABELS_FA[s.code]) {
        STUDENT_TASK_LABELS_FA[s.code] = taskFa
      }
      if (procCode && s.code && taskFa) {
        PROCESS_STUDENT_TASK_LABELS_FA[procCode][s.code] = taskFa
      }
      const operatorTaskFa = (s.metadata?.operator_task_fa || '').trim()
      if (s.code && operatorTaskFa && !OPERATOR_TASK_LABELS_FA[s.code]) {
        OPERATOR_TASK_LABELS_FA[s.code] = operatorTaskFa
      }
      if (procCode && s.code && operatorTaskFa) {
        PROCESS_OPERATOR_TASK_LABELS_FA[procCode][s.code] = operatorTaskFa
      }
    }
  } catch (e) {
    console.error(f, e.message)
  }
}

const header = `/** Auto-generated by scripts/generate_process_metadata_labels.js from metadata/processes — do not edit by hand */
`

const body = `${header}export const PROCESS_LABELS_FA = ${JSON.stringify(PROCESS_LABELS_FA, null, 2)}

export const STATE_LABELS_FA = ${JSON.stringify(STATE_LABELS_FA, null, 2)}

export const STUDENT_TASK_LABELS_FA = ${JSON.stringify(STUDENT_TASK_LABELS_FA, null, 2)}

export const PROCESS_STATE_LABELS_FA = ${JSON.stringify(PROCESS_STATE_LABELS_FA, null, 2)}

export const PROCESS_STUDENT_TASK_LABELS_FA = ${JSON.stringify(PROCESS_STUDENT_TASK_LABELS_FA, null, 2)}

export const OPERATOR_TASK_LABELS_FA = ${JSON.stringify(OPERATOR_TASK_LABELS_FA, null, 2)}

export const PROCESS_OPERATOR_TASK_LABELS_FA = ${JSON.stringify(PROCESS_OPERATOR_TASK_LABELS_FA, null, 2)}
`

const outPath = path.join(root, 'admin-ui', 'src', 'utils', 'processMetadataLabels.js')
fs.writeFileSync(outPath, body, 'utf8')
console.log(
  'Wrote', outPath,
  'processes:', Object.keys(PROCESS_LABELS_FA).length,
  'states:', Object.keys(STATE_LABELS_FA).length,
  'student_tasks:', Object.keys(STUDENT_TASK_LABELS_FA).length,
  'operator_tasks:', Object.keys(OPERATOR_TASK_LABELS_FA).length,
)
