/**
 * Generates admin-ui/src/utils/processMetadataLabels.js from metadata/processes/*.json
 * Run from repo root: node scripts/generate_process_metadata_labels.js
 */
const fs = require('fs')
const path = require('path')

const root = path.join(__dirname, '..')
const dir = path.join(root, 'metadata', 'processes')
const STATE_LABELS_FA = {}
const PROCESS_LABELS_FA = {}

for (const f of fs.readdirSync(dir).filter((x) => x.endsWith('.json'))) {
  try {
    const j = JSON.parse(fs.readFileSync(path.join(dir, f), 'utf8'))
    if (j.process?.code && j.process?.name_fa) {
      PROCESS_LABELS_FA[j.process.code] = j.process.name_fa
    }
    for (const s of j.states || []) {
      if (s.code && s.name_fa && !STATE_LABELS_FA[s.code]) {
        STATE_LABELS_FA[s.code] = s.name_fa
      }
    }
  } catch (e) {
    console.error(f, e.message)
  }
}

const header = `/** Auto-generated by scripts/generate_process_metadata_labels.js from metadata/processes — do not edit by hand */
`

const body = `${header}export const PROCESS_LABELS_FA = ${JSON.stringify(PROCESS_LABELS_FA, null, 2)}

export const STATE_LABELS_FA = ${JSON.stringify(STATE_LABELS_FA, null, 2)}
`

const outPath = path.join(root, 'admin-ui', 'src', 'utils', 'processMetadataLabels.js')
fs.writeFileSync(outPath, body, 'utf8')
console.log('Wrote', outPath, 'processes:', Object.keys(PROCESS_LABELS_FA).length, 'states:', Object.keys(STATE_LABELS_FA).length)
