"""Generate admin-ui/src/utils/smsTemplateLabels.js from notification templates."""

from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
NOTIF = ROOT / "app/services/notification_service.py"
PATTERN_MAP = ROOT / "metadata/sms_template_pattern_map.json"
OUT = ROOT / "admin-ui/src/utils/smsTemplateLabels.js"


def _process_metadata_labels() -> dict[str, str]:
    import sys

    sys.path.insert(0, str(ROOT))
    from app.services.sms_process_template_texts import process_sms_template_texts

    out: dict[str, str] = {}
    for key, text in process_sms_template_texts().items():
        hint = (text or key).replace("\n", " ")[:72].strip()
        out[key] = hint or key.replace("_", " ")
    return out


def main() -> None:
    text = NOTIF.read_text(encoding="utf-8")
    keys = re.findall(r'^\s+"([a-z0-9_]+)":\s*\{', text, re.M)
    labels: dict[str, str] = {}
    for k in keys:
        m = re.search(rf'"{re.escape(k)}":\s*\{{[^}}]*"sms":\s*"([^"{{]+)', text)
        hint = (m.group(1)[:72] if m else k.replace("_", " ")).strip()
        labels[k] = hint

    pm = json.loads(PATTERN_MAP.read_text(encoding="utf-8"))
    for k in pm.get("mappings", {}):
        labels.setdefault(k, k.replace("_", " "))

    for k in ("otp_login", "student_portal_welcome_credentials"):
        labels.setdefault(k, k.replace("_", " "))

    for k, hint in _process_metadata_labels().items():
        labels.setdefault(k, hint)

    lines = [
        "/** Auto-generated by scripts/generate_sms_template_labels.py — do not edit by hand */",
        "",
        "export const SMS_TEMPLATE_LABELS_FA = " + json.dumps(labels, ensure_ascii=False, indent=2),
        "",
        "const KIND_LABELS = {",
        "  otp: 'کد ورود',",
        "  notification: 'اعلان فرایند',",
        "  pattern: 'پترن ملی‌پیامک',",
        "  free_text: 'پیام آزاد',",
        "}",
        "",
        "export function humanizeTemplateKey(key) {",
        "  if (!key) return ''",
        "  return String(key).replace(/_/g, ' ')",
        "}",
        "",
        "/** @param {string | null | undefined} templateKey @param {string | undefined} kind */",
        "export function getSmsTemplateLabel(templateKey, kind) {",
        "  if (templateKey && SMS_TEMPLATE_LABELS_FA[templateKey]) {",
        "    return SMS_TEMPLATE_LABELS_FA[templateKey]",
        "  }",
        "  if (kind && KIND_LABELS[kind]) return KIND_LABELS[kind]",
        "  if (templateKey) return humanizeTemplateKey(templateKey)",
        "  return kind && KIND_LABELS[kind] ? KIND_LABELS[kind] : 'پیامک'",
        "}",
        "",
    ]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {len(labels)} labels to {OUT}")


if __name__ == "__main__":
    main()
